In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
X = df.drop('sales',axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
X.shape

(200, 3)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [13]:
X_train.shape

(140, 19)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [19]:
X_train = scaler.transform(X_train)

In [20]:
X_test = scaler.transform(X_test)

In [22]:
X_train[0]

array([-1.81079901, -1.4683538 , -1.42107822, -1.18338519, -1.10029124,
       -0.95155786, -1.05506139, -0.89977401, -0.79587121, -0.9339174 ,
       -0.85411893, -0.72397979, -0.82050449, -0.6910803 , -0.58978893,
       -0.84796655, -0.72629643, -0.61592631, -0.54660144])

In [28]:
from sklearn.linear_model import Ridge
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [29]:
ridge_model = Ridge(alpha=10)

In [30]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [33]:
test_predictions = ridge_model.predict(X_test)

In [34]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [36]:
MAE = mean_absolute_error(y_test,test_predictions)

In [37]:
MAE

0.4126894937074204

In [39]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [40]:
from sklearn.linear_model import RidgeCV

In [46]:
ridge_cv_model = RidgeCV(alphas = (0.1,1.0,10.0), scoring = 'neg_mean_absolute_error')

In [47]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [48]:
ridge_cv_model.alpha_

10.0

In [44]:
# from sklearn.metrics import SCORERS

In [50]:
test_predictions = ridge_cv_model.predict(X_test)

In [51]:
MAE = mean_absolute_error(y_test,test_predictions)

In [52]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [53]:
MAE

0.5587941998054606

In [54]:
RMSE

0.7439500368528859

In [55]:
ridge_cv_model.coef_

array([ 8.51968371e-02,  2.99658968e-02,  1.20416099e-02, -4.07134046e-04,
        1.55118125e-03, -3.34145745e-04, -1.74740478e-03,  8.97282458e-04,
        2.56929015e-04,  7.67067831e-07, -1.82210897e-06,  1.04985611e-06,
        2.60074012e-06, -1.73009357e-06,  1.90484570e-08,  2.18357741e-05,
       -8.51576368e-06, -3.72348359e-06, -1.91819800e-06])

In [56]:
ridge_cv_model.best_score_

-0.366680184284251

In [57]:
from sklearn.linear_model import LassoCV

In [61]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100,cv=5)

In [62]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [63]:
lasso_cv_model.alpha_

2395431.0622080103

In [64]:
test_predictions = lasso_cv_model.predict(X_test)

In [65]:
MAE = mean_absolute_error(y_test,test_predictions)

In [66]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [67]:
MAE

3.0345651452387568

In [68]:
RMSE

3.745703391460285

In [69]:
lasso_cv_model.coef_

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.26656276e-07, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [70]:
from sklearn.linear_model import ElasticNetCV

In [71]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001,n_alphas=100,max_iter=1000000)

In [72]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [73]:
elastic_model.l1_ratio_

1.0

In [74]:
elastic_model.alpha_

23954.310622080102

In [75]:
lasso_cv_model.alpha_

2395431.0622080103

In [76]:
test_predictions = elastic_model.predict(X_test)

In [77]:
MAE = mean_absolute_error(y_test,test_predictions)

In [78]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [79]:
MAE

1.3018706584630586